f/2209131121/decoupling-collection-name
struxhub/github_actions pull request #5
Opened 2022-09-28 09:57 UTC by vonoshko

2022-10-06 15:10 UTC, roman-bilyi requested changes
Check the comment.

2022-10-11 15:31 UTC, roman-bilyi approved these changes

2022-10-12 18:19 UTC, roman-bilyi requested changes

2022-10-12 18:19 UTC, roman-bilyi commented on .github/workflows/command-test-collection.yml
> +            kubectl set env ${{ steps.vars.outputs.deploymentName }} "$testCollectionEnv"
we could avoid the `for` cycle:
`$ kubectl set env RESOURCE/NAME KEY_1=VAL_1 ... KEY_N=VAL_N`
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-env-em-

Actually, this will clean up a lot this workflow as we don't have to parse env pairs.

2022-10-12 18:19 UTC, roman-bilyi commented on .github/workflows/command-test-collection.yml
> +          kubectl set env ${{ steps.vars.outputs.deploymentName }} --list
We should not expose env variables to github logs. or any logs.

2022-10-13 11:10 UTC, vonoshko commented on .github/workflows/command-test-collection.yml
> +          kubectl set env ${{ steps.vars.outputs.deploymentName }} --list
I just want to check the result and then I`ll remove it)

2022-10-18 11:00 UTC, merged